#Pandas Example

#Write a Pandas program to create and display a one-dimensional array using series  containing  even numbers upto 10

In [4]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8,10]) 
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64


#Write a Pandas program to convert a Panda module Series to Python list and its type.


In [5]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


#Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [6]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


##Write a Pandas program to compare the elements of the two Pandas Series.
#Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [7]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


#Write a Pandas program to convert a dictionary to a Pandas series.
#Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}

In [34]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)

Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


#Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50]

In [9]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


#Write a Pandas program to change the data type of the given  Series into numeric
#['100', '200', 'python', '300.12', '400']


In [10]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)

Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


# Write a Pandas program to convert a given Series to an array.

In [11]:
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


#Write a Pandas program to sort a given Series.

In [13]:
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)


Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


#Write a Pandas program to add some data to an existing Series.


In [14]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


#Write a Pandas program to create a subset of a given series based on value and condition.

In [15]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


#Write a Pandas program to change the order of index of a given series.

In [16]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.

In [17]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


#Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}

In [18]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


#Write a Pandas program to get the columns of the DataFrame (movies_metadata.csv file).


In [40]:
import pandas as pd 
import numpy as np 
import io
from google.colab import files 
uploaded = files.upload()
df2 = pd.read_csv(io.BytesIO(uploaded['movies_metadata.csv']))
print("Columns of the DataFrame:")
print(df.columns)

Saving movies_metadata.csv to movies_metadata (2).csv


ParserError: ignored

#Write a Pandas program to sort the DataFrame based on country from dataset of 
# movie_metadata.csv

In [37]:
import pandas as pd 
import numpy as np 
import io

from google.colab import files 
uploaded = files.upload()
df2 = pd.read_csv(io.BytesIO(uploaded['movies_metadata.csv']))
print("sorted by country")
small_df = df[['num_user_for_reviews','language','country','content_rating','budget','title_year']]
result = small_df.sort_values('country')
print("DataFrame based on release date.")
print(result)


Saving movies_metadata.csv to movies_metadata (2).csv


ParserError: ignored

#Write a Pandas program to get the details of the thrid movie of the DataFrame #(movie_metadata.csv file).

In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
third_movie = df.iloc[2]
print("Details of the third moviee:")
print(third_movie)

#Write a Pandas program to display the first 10 rows of the DataFrame.

In [ ]:
import pandas as pd
df = pd.read_csv('/home/cyborg/Desktop/Data analytics/programs/movie_metadata.csv')
#Display the first 10 rows
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)

#Numpy Examples

#Write a NumPy program to generate five random numbers from the normal distribution.

In [20]:
import numpy as np
x = np.random.normal(size=5)
print(x)

[-1.74073916 -1.3930055   0.20943402  0.56934508 -0.46622132]


#Write a NumPy program to generate six random integers between 10 and 30

In [21]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[20 26 19 22 18 27]


#Write a NumPy program to create a 3x3x3 array with random values.

In [22]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.97378813 0.21132569 0.01091695]
  [0.84743796 0.49866743 0.17310055]
  [0.34059471 0.1011117  0.75539027]]

 [[0.08586802 0.98289804 0.81359142]
  [0.81161214 0.31832926 0.12904057]
  [0.04147392 0.93897019 0.5711108 ]]

 [[0.73861247 0.41406424 0.88805748]
  [0.56806968 0.53690567 0.19526353]
  [0.84951959 0.10532097 0.10893721]]]


#Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values.

In [23]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.03980643 0.06152395 0.43573354 0.66765522 0.65054763]
 [0.06819788 0.04490503 0.59919599 0.64162056 0.73283951]
 [0.93336997 0.66699078 0.00803485 0.69332793 0.09747816]
 [0.2504963  0.91180811 0.45783986 0.41664043 0.20203981]
 [0.20919732 0.34404918 0.26730084 0.66700929 0.92379147]]
Minimum and Maximum Values:
0.008034853342496096 0.9333699688346037


#Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [24]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)

Original array: 
[[5.02731367e-01 9.06598991e-02 3.76084417e-01 6.33114716e-01]
 [6.28980404e-01 5.72296439e-01 5.85988523e-01 3.30784763e-01]
 [1.40009295e-01 7.27696783e-01 5.65225505e-01 3.74315657e-01]
 [2.44813680e-01 2.09416622e-01 1.89391201e-01 6.28145104e-01]
 [7.25492183e-01 6.16185491e-01 9.74953614e-01 5.37963132e-01]
 [8.52889250e-01 6.23446053e-01 7.97872395e-01 8.72516203e-01]
 [5.57429733e-01 8.06274506e-01 9.17052931e-01 5.97697230e-05]
 [9.82938562e-01 6.18917572e-01 8.56225441e-01 6.55117705e-01]
 [8.13571540e-01 7.88135194e-02 3.49400184e-01 9.90756219e-01]
 [8.71203362e-01 9.73573596e-02 1.53308780e-01 8.33658056e-01]]
First 5 rows of the above array:
[[0.50273137 0.0906599  0.37608442 0.63311472]
 [0.6289804  0.57229644 0.58598852 0.33078476]
 [0.1400093  0.72769678 0.56522551 0.37431566]
 [0.24481368 0.20941662 0.1893912  0.6281451 ]
 [0.72549218 0.61618549 0.97495361 0.53796313]]
First 3 columns of the above array:
[[5.02731367e-01 9.06598991e-02 3.76084417e-01 

#Write a NumPy program to shuffle numbers and find permutation  between 0 and 10 (inclusive).

In [25]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

[0 5 8 6 1 7 2 3 9 4]
Same result using permutation():
[1 3 6 0 9 2 4 7 8 5]


#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [33]:
import numpy as np
x=np.arange(10)
np.random.randint(x)
print (x)


ValueError: ignored

#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [31]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)


[7 3 9 1 6 8 0 5 2 4]
[0 1 2 3 4 5 6 7 8 9]
